In [29]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [30]:
df = pd.read_csv('train.txt' , sep=';' , header= None , names =['text','emotion'])

In [31]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [32]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [33]:
unique_emotions = df['emotion'].unique()
#create a dictionary to save emotions 
emotion_numbers ={} 
#give numeric values to the emotions 
i = 0
for emo in unique_emotions:
    emotion_numbers[emo] = i 
    i+=1 

df['emotion'] = df['emotion'].map(emotion_numbers)

In [34]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [35]:
#converting all texts in lower case 

df['text'] = df['text'].apply(lambda x:x.lower())

In [36]:
#remove puncuations :-
import string 
def remove_punc(text):
    return text.translate(str.maketrans('','' ,string.punctuation))

In [37]:
df['text'] = df['text'].apply(remove_punc)

In [38]:
#now remove numbers 
def remove_numbers(text):
    new =""
    for i in text:
        if not i.isdigit():
            new = new + i
    return new 
df['text'] = df['text'].apply(remove_numbers)

In [39]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [40]:
#remove urls and links 
import re

def remove_urls(text):
    if isinstance(text, str):
        return re.sub(r'http\S+|www\S+', '', text)
    return text
df['text'] = df['text'].apply(remove_urls)

In [41]:
#remove emojies and special characters :-
def remove_emojis(text):
    new = ""
    for i in text:
        if i.isascii():
            new += i 
    return new 

df['text']=df['text'].apply(remove_emojis)

In [42]:
#remove stopwords :-
import nltk

In [43]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize

In [44]:
nltk.download("punkt")   #used for tokenization
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shiva\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shiva\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [45]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [46]:
len(stop_words)

198

In [47]:
#tokenization 
def remove(text):
    if isinstance(text, str):
        words = word_tokenize(text)
        cleaned = []
        for i in words:
            if i not in stop_words:
                cleaned.append(i)
        return ' '.join(cleaned)
    return text

In [48]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\shiva\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [49]:
df['text'] = df['text'].apply(remove)

In [50]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [53]:
#now lets split the text means make text and emotion seprate in ratio of 80:20 

from sklearn.model_selection import train_test_split

x=df['text']
y=df['emotion']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.20, random_state=42)

In [54]:
x_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [55]:
x_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
15578    feel useful pulpit find ironic often question ...
5746             dried bladders ready day im feeling brave
6395                             feel thrilled matter days
7624     woke morning text mr c declaring walking work ...
15245                                            feel dumb
Name: text, Length: 3200, dtype: object

In [57]:
#CountVectorizer is for bag of words which contain only 0 and 1 
# Tfidf is for term frequencies IDFs ko calculate krta hai aur uske basis pe apaka points m,e deta hai

In [58]:
#1st model using bag of words

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer , CountVectorizer

from sklearn.naive_bayes import MultinomialNB 
from sklearn.metrics import accuracy_score

bow_vactorizer = CountVectorizer()
x_train_bow = bow_vactorizer.fit_transform(x_train)
x_test_bow = bow_vactorizer.transform(x_test)
#using navbias model 
nb_model = MultinomialNB()
nb_model.fit(x_train_bow,y_train)

pred_bow = nb_model.predict(x_test_bow)
print("Accuracy:", accuracy_score(y_test,pred_bow))

Accuracy: 0.7678125

In [72]:
pred_bow

array([0, 5, 0, ..., 5, 5, 0])

In [73]:
#now do by using TfidfVectorizer

In [74]:
Tfidf_Vectorizer  =  TfidfVectorizer()

x_train_tfidf = Tfidf_Vectorizer.fit_transform(x_train)
x_test_tfidf = Tfidf_Vectorizer.transform(x_test)


nb2_model = MultinomialNB ()
nb2_model.fit(x_train_tfidf,y_train)

MultinomialNB()

In [75]:
#lets predict 
y_pred = nb2_model.predict(x_test_tfidf)
print("Accuracy:", accuracy_score(y_test,y_pred))

Accuracy: 0.6609375

In [76]:
#lets use logistic regression using tf-idf and make a model 

from sklearn.linear_model import LogisticRegression

In [78]:
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(x_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [79]:
#now test 
log_pred = logistic_model.predict(x_test_tfidf)

In [80]:
print("Accuracy:" , accuracy_score(y_test,log_pred))

Accuracy: 0.8621875